add API delete all by id
worxid/worx pull request #141
Opened 2022-11-03 07:21 UTC by dwiky-valid

2022-11-04 06:35 UTC, mohisasarwono16 requested changes
Maaf mas, udah OK mas, tapi ada catatan sedikit.

2022-11-04 06:35 UTC, mohisasarwono16 commented on application/src/main/java/id/worx/worx/service/devices/DeviceWebWebServiceImpl.java
> +        List<Device> devices = deviceRepository.findByIds(ids);
Maaf mas mungkin yang ini bisa pakai yang deviceRepository.deleteAll(list). Jadi si iterationnya nggak dipake mas

2022-11-04 07:03 UTC, mohisasarwono16 commented on application/src/main/java/id/worx/worx/service/devices/DeviceWebWebServiceImpl.java
> +        List<Device> devices = deviceRepository.findByIds(ids);
Ehh saya salah mas, saya kira ini hard delete ternyata soft delete

2022-11-04 07:06 UTC, mohisasarwono16 submitted a review, later dismissed
Udah OK mas

2022-11-04 07:19 UTC, dwiky-valid commented
mas mo ini udah oke blm? gw bingung wkwkw

2022-11-07 03:12 UTC, shygnome requested changes
@dwiky-valid @aliansyahkay ada feedback ya

2022-11-07 03:12 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/devices/DeviceWebService.java
> +
dua method ini boleh direfactor supaya punya nama yg sama? nanti beda di parameternya.

contoh referensi kayak gini.
https://github.com/worxid/worx/blob/05b3953b3d23eba610443db2cf16bcdcff76c322/application/src/main/java/id/worx/worx/service/FormTemplateService.java#L28-L32

2022-11-07 03:12 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/devices/DeviceWebWebServiceImpl.java
> +        List<Device> devices = deviceRepository.findByIds(ids);
ini bisa diganti pakai `findAllById` bawaan dari jpa.

2022-11-07 03:12 UTC, shygnome commented on application/src/main/java/id/worx/worx/repository/DeviceRepository.java
> +
ini kalo gak dipake nanti boleh dihapus. bisa pakai langsung bawaan `findAllById`.

2022-11-09 02:31 UTC, shygnome approved these changes
lgtm

2022-11-09 02:35 UTC, merged