add cronjob to delete expired token
worxid/worx pull request #168
Opened 2022-11-09 07:55 UTC by dwiky-valid

2022-11-09 08:06 UTC, shygnome requested changes
@dwiky-valid ada feedback

2022-11-09 08:06 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    @Scheduled(cron = "* * * * * ?")
ini cron-nya dibikin 1 kali per hari aja. langsung cek di jam 23:59:59.

2022-11-09 08:06 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    @Scheduled(cron = "* * * * * ?")
ini cron-nya dibikin 1 kali per hari aja. langsung cek di jam 23:59:59.

2022-11-09 08:06 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    public void deleteRefreshToken() throws Exception{
boleh tambahin anotasi `@Transactional`. Karena kita melakukan delete

2022-11-09 08:06 UTC, shygnome commented on application/src/main/java/id/worx/worx/repository/RefreshTokenRepository.java
> +    void deleteAllByDate(String date);
ini coba jangan pakai native query dulu kalo bisa.

sama tambahan boleh dicari tau apa perlu anotasi `@Modifying(clearAutomatically = true, flushAutomatically = true)`. 

atau kalo mau yg paling aman, di sisi repository cukup `findAll` yg expired aja. nanti di sisi service yg melakukan `deleteAll`

2022-11-09 08:06 UTC, shygnome commented on application/src/main/java/id/worx/worx/repository/EmailTokenRepository.java
> +    void deleteAllByDate(String date);
ini coba jangan pakai native query dulu kalo bisa.

sama tambahan boleh dicari tau apa perlu anotasi `@Modifying(clearAutomatically = true, flushAutomatically = true)`. 

atau kalo mau yg paling aman, di sisi repository cukup `findAll` yg expired aja. nanti di sisi service yg melakukan `deleteAll`

2022-11-15 02:49 UTC, shygnome requested changes
@dwiky-valid ada feedback

2022-11-15 02:49 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +        if(checkData.get().getExpiredToken().compareTo(Instant.now()) >= 0){
ini bisa pake built-in method `isAfter` atau `isBefore`

2022-11-15 02:49 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +        if(checkToken.get().getExpiredToken().compareTo(Instant.now()) >= 0){
ini bisa pake built-in method `isAfter` atau `isBefore`

2022-11-15 02:49 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    @Scheduled(cron = "59 23 * * * ?")
ini boleh dicek ya, cron-nya harusnya `"59 59 23 * * ?"`

2022-11-15 02:49 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    @Scheduled(cron = "59 23 * * * ?")
ini boleh dicek ya, cron-nya harusnya `"59 59 23 * * ?"`

2022-11-15 03:36 UTC, dwiky-valid commented on application/src/main/java/id/worx/worx/service/users/UsersServiceImpl.java
> +    @Scheduled(cron = "59 23 * * * ?")
![image](https://user-images.githubusercontent.com/106949374/201820506-1dabea48-5329-4d50-958c-09fd6606e8f9.png)
untuk crontab sptnya gak bisa mas.. mungkin ya.
jadinya harus 59 23 * * *

2022-11-15 06:29 UTC, merged