add API dashboard bar stats
worxid/worx pull request #224
Opened 2022-11-23 07:52 UTC by dwiky-valid

2022-11-23 09:18 UTC, shygnome requested changes
@dwiky-valid secara hasil udah oke. ada catatan dari segi implementasi.

2022-11-23 09:18 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/dashboard/DashboardServiceImpl.java
> +                responses.add(dashboardStatDTO);
bagian ini bisa dikeluarin dari klausa if supaya gak berkali2

2022-11-23 09:18 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/dashboard/DashboardServiceImpl.java
> +                Integer count = formRepository.getCountByRespondentDeviceAndTemplateId(startDate,endDate,deviceCode, dashboardRequest.getFormId());
untuk bagian ini lebih ke pertanyaan dulu. apa bisa dapet count-nya langsung semua?

soalnya cost-nya lumayan di sini panggil sql per jumlah date-nya.

kalo bisa boleh diubah supaya panggil sql-nya cukup sekali.

2022-11-23 09:18 UTC, shygnome commented on application/src/main/java/id/worx/worx/repository/FormRepository.java
> +    Integer getCountByDateOnly(Instant startDate,Instant endDate);
untuk ini mungkin bisa pakai `Specification`? supaya gak perlu repot nanti kalo ada tambah parameter lagi.

2022-11-23 17:29 UTC, dwiky-valid commented on application/src/main/java/id/worx/worx/service/dashboard/DashboardServiceImpl.java
> +                Integer count = formRepository.getCountByRespondentDeviceAndTemplateId(startDate,endDate,deviceCode, dashboardRequest.getFormId());
sebenernya disini gw ada pikiran mau bikin sql group by `submit_date ` apa kira2 ini mau di bikin kayak sql grouping by date aja?

2022-11-24 03:00 UTC, shygnome commented on application/src/main/java/id/worx/worx/service/dashboard/DashboardServiceImpl.java
> +                Integer count = formRepository.getCountByRespondentDeviceAndTemplateId(startDate,endDate,deviceCode, dashboardRequest.getFormId());
boleh kalo mau di group by submit_date, tapi di-filter dulu by from to nya baru digrouping, supaya yg di group lebih sedikit

2022-11-28 15:17 UTC, merged