Update group api
worxid/worx pull request #324
Opened 2022-12-26 03:17 UTC by dwiky-valid

2022-12-27 02:48 UTC, shygnome requested changes
ada feedback, boleh diperbaiki

2022-12-27 02:48 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/DeviceGroups.java
> +}
ini gak perlu dibuat class entity-nya. udah dibuat dari join table di class masing2.

https://github.com/worxid/worx/blob/f07350972f34fc1fe6e7fcb1db5e7416a97f8724/application/src/main/java/id/worx/worx/entity/devices/Device.java#L60-L67
https://github.com/worxid/worx/blob/f07350972f34fc1fe6e7fcb1db5e7416a97f8724/application/src/main/java/id/worx/worx/entity/Group.java#L57-L64

2022-12-27 02:48 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/DeviceGroups.java
> +}
cara update mirip seperti di sini, cuma bisa diubah sedikit logic-nya disesuaikan untuk update semua device yg efektif kena update. https://github.com/worxid/worx/blob/f07350972f34fc1fe6e7fcb1db5e7416a97f8724/application/src/main/java/id/worx/worx/service/devices/DeviceServiceImpl.java#L190-L209

2022-12-27 02:48 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/TemplateGroups.java
> +    private Long groupId;
ini gak perlu dibuat class entity-nya. udah dibuat dari join table di class masing2.

https://github.com/worxid/worx/blob/f07350972f34fc1fe6e7fcb1db5e7416a97f8724/application/src/main/java/id/worx/worx/entity/FormTemplate.java#L66-L74

https://github.com/worxid/worx/blob/f07350972f34fc1fe6e7fcb1db5e7416a97f8724/application/src/main/java/id/worx/worx/entity/Group.java#L50-L57

2022-12-30 04:24 UTC, dwiky-valid commented
https://github.com/worxid/worx/pull/336
maaf mas jadi ke create branch baru mas hehe

2023-01-03 06:00 UTC, closed without merging