[WIP ] Authentication and Devices
worxid/worx pull request #44
Opened 2022-09-13 21:47 UTC by aliansyahkay

2022-09-28 10:11 UTC, shygnome requested changes
@dwiky-valid @aliansyahkay ada beberapa revisi terutama di bagian penamaan.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/devices/Devices.java
> +@Table(name = "DEVICES")
penamaannya tabelnya lower case aja ya `devices`.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/devices/Devices.java
> +    @Column(name = "DEVICE_NO", nullable = false)
penamaannya column-nya dibiarkan id aja sesuai di ERD.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/RefreshToken.java
> +    @JoinColumn(name = "ID", referencedColumnName = "id")
ini join column-nya `user_id` ya, biar jelas konteks-nya.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/RefreshToken.java
> +@Table(name = "refresh_token")
kita pakai convention plural buat nama tabel ya. yg berarti di sini `refresh_tokens`.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Role.java
> +@Table(name = "ROLE")
kita pakai convention lower case + plural buat nama tabel ya. yg berarti di sini `roles`.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/TokenHistory.java
> +@Table(name = "token_history")
ini nama class-nya kayaknya kurang tepat, mungkin EmailToken `email_tokens`? atau mungkin boleh dicari lagi nama yg sesuai.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/TokenHistory.java
> +    private String type;
dua field ini `status` dan `type` mungkin bisa pakai enum supaya bisa tau ada nilai apa aja.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +@Table(name = "USERS")
lower case ya.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +    @Column(name = "ID", nullable = false)
nama column bisa dibuat lower case semua + kalo memang namanya sama dengan nama variable bisa dikosongin bagian `name`.

2022-09-28 10:11 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +}
4 method ini apa sudah diimplementasi? kenapa return `true` semua?

2022-09-29 06:59 UTC, dwiky-valid commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +}
mas ini gw liat di tutorial sih.. kl gw apus soalnya berhubungan sama token nya.enaknya gimana?

2022-09-29 07:03 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +}
cuma mastiin aja. kalo emang implementasinya cuma return `true` gak ada masalah. takutnya ada yg ketinggalan aja.

2022-09-29 07:05 UTC, dwiky-valid commented on application/src/main/java/id/worx/worx/entity/users/Users.java
> +}
oh okee.. soalnya kl gw apus itu ada eror di check jwt nya, gw solve aja ya?

2022-09-30 02:31 UTC, shygnome requested changes
@aliansyahkay @dwiky-valid ada revisi lagi soal penamaan di request/response.

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/entity/users/Users.java
nama tabelnya masih `USERS` ya, boleh dibuat lower case jadi `users`.

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/request/FieldCondition.java
> +    private Objects searchedValue;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/request/auth/ChangePasswordRequest.java
> +    private String newPassword;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/request/auth/ChangePasswordToken.java
> +    private String newPassword;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/request/auth/TokenRefreshRequest.java
> +    private String refreshToken;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/request/users/UserRequest.java
> +    private String country;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/response/auth/TokenRefreshResponse.java
> +    private String tokenType = "Bearer";
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 02:31 UTC, shygnome commented on application/src/main/java/id/worx/worx/model/response/users/UserResponse.java
> +    private Long userId;
ini boleh dibuat jadi snake case? pakai @JsonProperty. kita buat standar request response-nya dibuat jadi snake case di json.

```java
@JsonProperty("field_name")
private String fieldName;
@JsonProperty("searched_value")
private Objects searchedValue;
```

2022-09-30 07:35 UTC, shygnome approved these changes
lgtm

2022-09-30 07:36 UTC, merged